package:
  name: malleefowl
  version: !!str 0.3.11

source:
  git_url: https://github.com/bird-house/malleefowl.git
  git_tag: master
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - malleefowl = malleefowl:main
    #
    # Would create an entry point called malleefowl that calls malleefowl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 4

requirements:
  build:
    - python
    - setuptools
    - pywps
    - htmltmpl
    - python-magic
    - lxml
    - owslib
    - pyproj
    - pyyaml
    - netcdf4
    - dispel4py
    - esgf-pyclient
    - myproxyclient
    - python-swiftclient
    - threddsclient  
    - pysolr
    - nose

  run:
    - python
    - setuptools
    - pywps
    - htmltmpl
    - python-magic
    - lxml
    - owslib
    - pyproj
    - pyyaml
    - netcdf4
    - dispel4py
    - esgf-pyclient
    - myproxyclient
    - python-swiftclient
    - threddsclient  
    - pysolr
    - nose

test:
  # Python imports
  imports:
    - malleefowl

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  #requires:
    # Put any additional test requirements here.  For example
    #- nose

about:
  home: https://github.com/bird-house/malleefowl
  license: Apache License v2.0
  summary: 'Malleefowl provides access to climate data as a WPS service and library.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
