package:
  name: fiona
  version: !!str 1.4.8

source:
  fn: Fiona-1.4.8.tar.gz
  url: https://pypi.python.org/packages/source/F/Fiona/Fiona-1.4.8.tar.gz
  md5: 0fa065f5420e6901570ef87cea3cba35
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fiona = fiona:main
    #
    # Would create an entry point called fiona that calls fiona.main()

    - fio=fiona.fio.fio:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click
    - six

  run:
    - python
    - setuptools
    - click
    - six

test:
  # Python imports
  imports:
    - fiona
    - fiona.fio

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - fio --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD License
  summary: 'Fiona reads and writes spatial data files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
