
package:
    name: thredds
    version: 4.3.23

source:
    fn: thredds.war 
    url: ftp://ftp.unidata.ucar.edu/pub/thredds/4.3/4.3.23/thredds.war
    md5: d032618c3e9acfa860795e2f10a36f86

build:
    number: 0

requirements:
    build:
        - apache-tomcat

    run:
        - apache-tomcat

test:

about:
    home: http://www.unidata.ucar.edu/software/thredds/current/tds/
    license: 

