package:
  name: grib_api
  version: 1.14.2

source:
  fn: grib_api-1.14.2.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.14.2-Source.tar.gz
  md5: a3da20f368984e6e83cdf2041fa54229

requirements:
  build:
    - python
    - numpy
    - libgfortran
    - jasper
    - jpeg
  run:
    - python
    - numpy
    - libgfortran
    - jasper
    - jpeg
build:
  number: 0 
  detect_binary_files_with_prefix: true

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache License v2.0 (http://www.apache.org/licenses/)
  summary: The ECMWF GRIB API is an application program interface accessible from C, FORTRAN and Python programs developed for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.
