package:
  name: grib_api
  version: 1.13.0

source:
  fn: grib_api-1.13.0.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.13.0.tar.gz?api=v2
  md5: 3fdae4e771c486e5f660a073de1ecd8a

requirements:
  build:
    - python
    - numpy
    - jasper
#    - libnetcdf
  run:
    - python
    - numpy
    - jasper

build:
  number: 1 
  detect_binary_files_with_prefix: true

about:
  home: https://software.ecmwf.int/wiki/display/GRIB/Home
  license: Apache License v2.0 (http://www.apache.org/licenses/)
  summary: The ECMWF GRIB API is an application program interface accessible from C, FORTRAN and Python programs developed for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.
