package:
  name: redis
  version: 3.0.3

build:
  number: 0

source:
  fn: redis-3.0.3.tar.gz
  url: http://download.redis.io/releases/redis-3.0.3.tar.gz
  sha256: 1d08fa665b16d0950274dfbd47fbbcf3485e43e901021338640a0334666e9da5

about:
  home: http://redis.io
  license: BSD

