package:
    name: expat
    version: 2.1.0
source:
    fn: expat-2.1.0.tar.gz
    url: http://sourceforge.net/projects/expat/files/expat/2.1.0/expat-2.1.0.tar.gz/download

#requirements:
#  build:
#    - cmake

build:
    number: 1
