package:
  name: adagucserver
  version: !!str 1.9.3

source:
  hg_tag: 1.9.3
  hg_url: http://dev.knmi.nl/hg/adagucserver
  patches:
    - adagucserver.patch
build:
  number: 0

requirements:
  build:
    - proj4
    - libnetcdf
    - udunits
    - gdal
    - cairo
    - sqlite
    - postgresql
    - libxml2
    - freetype
    - curl
    - jpeg
    - libgd
    - libpng ==1.5.13
  run:
    - proj4
    - libnetcdf
    - udunits
    - gdal
    - cairo
    - sqlite
    - postgresql
    - libxml2
    - freetype
    - curl
    - jpeg
    - libgd
    - libpng ==1.5.13
#test:
#  commands:
#    - adagucserver

about:
  home: http://adaguc.knmi.nl/
  license: Apache License 2.0
  summary: ADAGUC Web Mapping Service (WMS) for NetCDF files used by climate science community.
