package:
  name: flower
  version: "0.8.2"

source:
  fn: flower-0.8.2.tar.gz
  url: https://pypi.python.org/packages/source/f/flower/flower-0.8.2.tar.gz
  md5: 613a4f2edf92f447ef556b9dceef968d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flower = flower:main
    #
    # Would create an entry point called flower that calls flower.main()

    - flower = flower.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - celery >=2.5.0
    - tornado >=4.0.0
    - babel
    - pytz
    - futures

  run:
    - python
    - setuptools
    - celery >=2.5.0
    - tornado >=4.0.0
    - babel
    - pytz
    - futures

test:
  # Python imports
  imports:
    - flower
    - flower.api
    - flower.utils
    - flower.utils.backports
    - flower.views

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - flower --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mher/flower
  license: BSD License
  summary: 'Celery Flower'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
