package:
  name: lapack
  version: 3.5.0

source:
  fn: lapack-3.5.0.tgz
  url: http://www.netlib.org/lapack/lapack-3.5.0.tgz
  sha1: 5870081889bf5d15fd977993daab29cf3c5ea970

build:
  number: 0 

requirements:
  build:
    - cmake
    - gcc

  run:
    - libgcc

about:
  home: http://www.netlib.org/lapack
  license: BSD
  summary: Linear Algebra PACKage
