package:
  name: lapack
  version: 3.4.1

source:
  fn: lapack-3.4.1.tgz
  url: http://www.netlib.org/lapack/lapack-3.4.1.tgz
  sha1: c115223ac1bac9ab971aae865d3e95442bc979bc

build:
  number: 0 

requirements:
  build:
    - gcc
    - blas

  run:
    - libgcc
    - blas

about:
  home: http://www.netlib.org/lapack
  license: BSD
  summary: Linear Algebra PACKage
