package:
  name: gunicorn
  version: 19.2.1

source:
  fn: gunicorn-19.2.1.tar.gz
  url: https://pypi.python.org/packages/source/g/gunicorn/gunicorn-19.2.1.tar.gz
  md5: 2d643e171dc20e2d182d8b11158d4401

build:
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_django=gunicorn.app.djangoapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - paste.deploy

test:
  imports:
    - gunicorn
  commands:
    - gunicorn --help
    - gunicorn_django --help
    - gunicorn_paster --help
  requires:
    - paste

about:
  home: http://gunicorn.org
  license: MIT License
  summary: 'WSGI HTTP Server for UNIX'
