package:
  name: gunicorn
  version: "19.3.0"

source:
  fn: gunicorn-19.3.0.tar.gz
  url: https://pypi.python.org/packages/source/g/gunicorn/gunicorn-19.3.0.tar.gz
  md5: faa3e80661efd67e5e06bba32699af20
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gunicorn = gunicorn:main
    #
    # Would create an entry point called gunicorn that calls gunicorn.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.management
    - gunicorn.management.commands
    - gunicorn.workers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - pytest
    - pytest-cov
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://gunicorn.org
  license: MIT License
  summary: 'WSGI HTTP Server for UNIX'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
