package:
  name: gunicorn
  version: 19.1.1

source:
  fn: gunicorn-19.1.1.tar.gz
  url: https://pypi.python.org/packages/source/g/gunicorn/gunicorn-19.1.1.tar.gz
  md5: eaa72bff5341c05169b76ce3dcbb8140

build:
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_django=gunicorn.app.djangoapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pastedeploy

test:
  imports:
    - gunicorn
  commands:
    - gunicorn --help
    - gunicorn_django --help
    - gunicorn_paster --help
  requires:
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT License
