package:
    name: compliance-checker
    version: "1.1.1"

source:
    git_url: https://github.com/ioos/compliance-checker.git
    git_tag: master

build:
    number: 1
    entry_points:
        - compliance-checker = cchecker:main

requirements:
    build:
        - python
        - setuptools
        - owslib
        - wicken
        - lxml
        - cf_units 
        - requests
        - python-dateutil
        - jinja2
    run:
        - python
        - owslib
        - wicken
        - lxml
        - cf_units
        - requests
        - python-dateutil
        - jinja2

test:
    imports:
        - compliance_checker
        - compliance_checker.cf
        - compliance_checker.tests
    commands:
        - compliance-checker --help

about:
    home: https://github.com/ioos/compliance-checker
    license:  Apache Software License
    summary: 'Checks Datasets and SOS endpoints for standards compliance'
