package:
  name: sphinxcontrib-dotnetdomain
  version: "0.4"

source:
  fn: sphinxcontrib-dotnetdomain-0.4.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-dotnetdomain/sphinxcontrib-dotnetdomain-0.4.tar.gz
  md5: 9d3c2d1b8debceffc17da75409bb1e14
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-dotnetdomain = sphinxcontrib-dotnetdomain:main
    #
    # Would create an entry point called sphinxcontrib-dotnetdomain that calls sphinxcontrib-dotnetdomain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=0.6

  run:
    - python
    - sphinx >=0.6

test:
  # Python imports
  imports:
    - sphinxcontrib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/rtfd/sphinxcontrib-dotnetdomain
  license: MIT License
  summary: 'Sphinx "dotnetdomain" extension'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
