package:
  name: flufl.enum
  version: "4.1.1"

source:
  fn: flufl.enum-4.1.tar.gz
  url: https://pypi.python.org/packages/21/a4/afb7213998ee8db590fd30fc0c665d6b7275e71ace33ef17836493884b7e/flufl.enum-4.1.1.tar.gz
  sha256: bla

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - flufl
    - flufl.enum
    - flufl.enum.docs
    - flufl.enum.tests

about:
  home: http://launchpad.net/flufl.enum
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'A Python enumeration package.'
  license_family: Public-Domain

extra:
  recipe-maintainers:
    - cehbrecht
