package:
  name: sphinxcontrib-golangdomain
  version: "0.1.3dev"

source:
  fn: sphinxcontrib-golangdomain-0.1.3dev.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-golangdomain/sphinxcontrib-golangdomain-0.1.3dev.tar.gz
  md5: 4aad8d0dc52e2dea97cd72b1599b2914
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-golangdomain = sphinxcontrib-golangdomain:main
    #
    # Would create an entry point called sphinxcontrib-golangdomain that calls sphinxcontrib-golangdomain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.0

  run:
    - python
    - sphinx >=1.0

test:
  # Python imports
  imports:
    - sphinxcontrib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/ymotongpoo/sphinxcontrib-golangdomain
  license: BSD License
  summary: 'Sphinx extension sphinxcontrib-golangdomain'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
