package:
    name: ncregrid
    version: 1.4b

source:
    #fn: ncregrid.tar.Z
    #url: http://www.pa.op.dlr.de/~PatrickJoeckel/ncregrid/ncregrid.tar.Z
    git_url: https://github.com/Kruecke/ncregrid.git

requirements:
    build:
        # We'll build 'libnetcdff' (for fortran) on our own in the build script, therefore:
        - gcc # For some stupid reason we have to have gcc/ld installed to install this... (Debian 8)
              # And we need 'make', but there doesn't seem to be a package on anaconda.
        - libnetcdf
    run:
        - gcc # We keep this one for the 'libquadmath' shared library. Maybe link it staticly? (TODO)
        - libnetcdf

test:
    commands:
        - ncregrid

about:
    home: http://www.pa.op.dlr.de/~PatrickJoeckel/ncregrid/
    summary: A tool for rediscretisation of geo-data
    license: GPL License
    license_file: ncregrid/LICENSE.txt
