package:
    name: netcdf-fortran
    version: 4.4.2

source:
    git_url: https://github.com/Unidata/netcdf-fortran
    git_tag: v4.4.2

build:
    number: 50
    skip: True  # [win]

requirements:
    build:
        - gcc
        - libnetcdf
        - krb5
    run:
        - gcc
        - libnetcdf
        - libgcc
        - krb5

test:
    commands:
        - nf-config --all

about:
    home: https://github.com/Unidata/netcdf-fortran
    license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
    summary: Unidata NetCDF Fortran Library
