package:
  name: pygeometa
  version: "0.1.0"

source:
  git_url: https://github.com/geopython/pygeometa.git
  git_branch: master

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysolr = pysolr:main
    #
    # Would create an entry point called pysolr that calls pysolr.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click
    - jinja2

  run:
    - python
    - click
    - jinja2

test:
  # Python imports
  imports:
    - pygeometa

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/geopython/pygeometa
  license: MIT License
  summary: 'pygeometa is a Python package to generate metadata for geospatial datasets.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
