package:
  name: pycsw
  version: "1.10.1"

source:
  fn: pycsw-1.10.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pycsw/pycsw-1.10.1.tar.gz
  md5: f13152c4b2d28cc86c1b946d39d74d30
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycsw = pycsw:main
    #
    # Would create an entry point called pycsw that calls pycsw.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - geolinks 
    - lxml
    - owslib
    - pyproj
    - shapely
    - psycopg2
    - sqlalchemy


  run:
    - python
    - geolinks 
    - lxml 
    - owslib 
    - pyproj 
    - shapely 
    - psycopg2
    - sqlalchemy

test:
  # Python imports
  imports:
    - pycsw

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pycsw.org/
  license: MIT License
  summary: 'pycsw is an OGC CSW server implementation written in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
