package:
  name: castf90
  version: 0.1.5

source:
  #git_url: https://github.com/sradanov/castf90
  git_url: https://github.com/bird-house/castf90
  #git_branch: master
  git_branch: pingudev 

build:
  number: 1
  features:
    - nomkl                   [nomkl]

requirements:
  build:
    - gcc
    - libgfortran             [linux]
    - netcdf-fortran
    - mkl                     [not nomkl]
    - openblas                [linux and nomkl]
    - lapack95

  run:
    - libgcc
    - libgfortran             [linux]
    - netcdf-fortran
    - mkl                     [not nomkl]
    - openblas                [linux and nomkl]
    - lapack95
    - cdo
    - nco

about:
  home: https://github.com/sradanov/castf90
  license: CeCILL FREE SOFTWARE LICENSE AGREEMENT
  summary: circulation analogue simulation tool in fortran95
