package:
  name: castf90
  version: 0.1.6

source:
  git_url: https://github.com/sradanov/castf90
  #git_url: https://github.com/bird-house/castf90
  git_branch: master
  #git_branch: pingudev 

build:
  number: 0

requirements:
  build:
    - gcc
    - libgfortran             [linux]
    - netcdf-fortran
    - mkl                     
    #- openblas                [linux]
    - lapack95

  run:
    - libgcc
    - libgfortran             [linux]
    - netcdf-fortran
    - mkl                     
    #- openblas                [linux]
    - lapack95
    - cdo
    - nco

about:
  home: https://github.com/sradanov/castf90
  license: CeCILL FREE SOFTWARE LICENSE AGREEMENT
  summary: circulation analogue simulation tool in fortran95
