package:
  name: docker-compose
  version: "1.4.2"

source:
  fn: docker-compose-1.4.2.tar.gz
  url: https://pypi.python.org/packages/source/d/docker-compose/docker-compose-1.4.2.tar.gz
  md5: e1aac29f3244a14b4a84532d5ace366a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docker-compose = docker-compose:main
    #
    # Would create an entry point called docker-compose that calls docker-compose.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docopt >=0.6.1,<0.7
    - pyyaml >=3.10,<4
    - requests >=2.6.1,<2.7
    - texttable >=0.8.1,<0.9
    - websocket-client >=0.32.0,<1.0
    - docker-py >=1.3.1,<1.4
    - dockerpty >=0.3.4,<0.4
    - six >=1.3.0,<2

  run:
    - python
    - docopt >=0.6.1,<0.7
    - pyyaml >=3.10,<4
    - requests >=2.6.1,<2.7
    - texttable >=0.8.1,<0.9
    - websocket-client >=0.32.0,<1.0
    - docker-py >=1.3.1,<1.4
    - dockerpty >=0.3.4,<0.4
    - six >=1.3.0,<2

test:
  # Python imports
  imports:
    - compose
    - compose.cli

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - flake8
    - mock >=1.0.1
    - nose
    - pyinstaller
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://www.docker.com/
  license: Apache License 2.0
  summary: 'Multi-container orchestration for Docker'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
