
package:
    name: pywps
    version: !!str 3.2dev

source:
    git_url: https://github.com/cehbrecht/PyWPS.git
    git_tag: master

build:
    number: 5 

requirements:
    build:
        - python
        - setuptools
        - htmltmpl
        - lxml
        - ordereddict
        - python-magic

    run:
        - python
        - htmltmpl
        - lxml
        - ordereddict
        - python-magic

test:
    imports:
        - pywps

    #commands:
    #    -

about:
    home: https://github.com/geopython/PyWPS
    license: GPLv2

