
package:
    name: pywps
    version: !!str 4.0.0_rc1

source:
    git_url: https://github.com/geopython/pywps.git
    git_tag: master

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
    run:
        - python
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - gdal 
test:
    imports:
        - pywps

    #commands:
    #    -

about:
    home: https://github.com/geopython/PyWPS
    license: MIT License
    summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.
