
package:
    name: pywps
    version: !!str 3.2.2

source:
    git_url: https://github.com/bird-house/PyWPS.git
    git_tag: pingudev

build:
    number: 11 

requirements:
    build:
        - python
        - setuptools
        - htmltmpl
        - lxml
        - python-magic

    run:
        - python
        - htmltmpl
        - lxml
        - python-magic

test:
    imports:
        - pywps

    #commands:
    #    -

about:
    home: https://github.com/geopython/PyWPS
    license: GPLv2
    summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.
