package:
  name: sphinx-autoapi
  version: "0.4.0"

source:
  fn: sphinx-autoapi-0.4.0.tar.gz
  url: https://pypi.python.org/packages/61/52/38d8652748e2172e5a2c96ee7487f8b35d6f0e2a790d8a28c5ef4a401578/sphinx-autoapi-0.4.0.tar.gz
  md5: b93b108db94aa5639fe1cbf6fbe43be9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinx-autoapi = sphinx-autoapi:main
    #
    # Would create an entry point called sphinx-autoapi that calls sphinx-autoapi.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - epyparse
    - epydoc
    - sphinx
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain
    - unidecode

  run:
    - python
    - pyyaml
    - epyparse
    - epydoc
    - sphinx
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain
    - unidecode

test:
  # Python imports
  imports:
    - autoapi
    - autoapi.mappers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ericholscher/sphinx-autoapi
  license: BSD
  summary: 'UNKNOWN'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
