package:
    name: pycsw
    version: "1.10.3"

source:
    git_url: https://github.com/geopython/pycsw.git
    git_tag: "1.10.3"

build:
    number: 0
    preserve_egg_dir: True

requirements:
    build:
        - python >=2.7,<3
    run:
        - python
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

about:
    home: https://github.com/geopython/pycsw
    license: MIT
    summary: 'OGC Catalog Service for the Web (CSW) implementation in python'
