{% set version = "0.3.5" %}

package:
  name: threddsclient
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/threddsclient.git
  git_tag: v{{ version }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - requests
    - beautifulsoup4
    - lxml
  run:
    - python
    - six
    - requests
    - beautifulsoup4
    - lxml

test:
  imports:
    - threddsclient

  requires:
    - pytest

about:
  home: https://github.com/bird-house/threddsclient
  license: Apache License v2.0
  summary: 'Thredds catalog client.'

extra:
  recipe-maintainers:
    - cehbrecht
