package:
  name: myproxyclient
  version: "1.4.3"

source:
  fn: MyProxyClient-1.4.3.tar.gz
  url: https://pypi.python.org/packages/source/M/MyProxyClient/MyProxyClient-1.4.3.tar.gz
  md5: 15d1dccae2cde5d24cd8fb082972debc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - myproxyclient = myproxyclient:main
    #
    # Would create an entry point called myproxyclient that calls myproxyclient.main()

    - myproxyclient = myproxy.script:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyopenssl

  run:
    - python
    - pyopenssl

test:
  # Python imports
  imports:
    - myproxy

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - myproxyclient --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cedadev/MyProxyClient
  license: GNU Library or Lesser General Public License (BSD)
  summary: 'This a pure Python implementation of a client to the MyProxy Credential Management Server.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
