package:
  name: wget
  version: 1.15

source:
  fn: wget-1.15.tar.gz
  url: http://ftp.gnu.org/gnu/wget/wget-1.15.tar.gz

build:
  number: 0

requirements:
  build:
    - zlib
    - openssl
  run:
    - zlib
    - openssl

test:
  commands:
    - wget --help

about:
  home: http://www.gnu.org/software/wget/
  license: GPL 3

# vim:set ts=8 sw=2 sts=2 tw=78 et:
