package:
  name: wget
  version: 1.16.3

source:
  fn: wget-1.16.3.tar.gz
  url: http://ftp.gnu.org/gnu/wget/wget-1.16.3.tar.gz

build:
  number: 1

requirements:
  build:
    - gcc
    - zlib
    - openssl
  run:
    - libgcc
    - zlib
    - openssl

test:
  commands:
    - wget --help

about:
  home: http://www.gnu.org/software/wget/
  license: GPL 3

# vim:set ts=8 sw=2 sts=2 tw=78 et:
