package:
  name: r-raster
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.3_24"

source:
  fn: raster_2.3-24.tar.gz
  url: http://cran.r-project.org/src/contrib/raster_2.3-24.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RColorBrewer, rgdal (>= 0.8-7), rgeos (>= 0.2-20), gstat
requirements:
  build:
    - r >=2.15.0
    - r-sp # [not win]

  run:
    - r >=2.15.0
    - r-sp # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('raster')" # [not win]
    - "\"%R%\" -e \"library('raster')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://cran.r-project.org/web/packages/raster/index.html
  license: GPL (>= 3)
  summary: Reading, writing, manipulating, analyzing and modeling of gridded spatial data. The package implements basic and high-level functions. Processing of very large files is supported.

# The original CRAN metadata for this package was:

