package:
  name: birdhouse-birdy
  version: !!str 0.1.3

source:
  fn: birdhouse-birdy-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/b/birdhouse-birdy/birdhouse-birdy-0.1.3.tar.gz
  md5: 958c3937cc5d0624d5535e6cbf159019
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - birdhouse-birdy = birdhouse-birdy:main
    #
    # Would create an entry point called birdhouse-birdy that calls birdhouse-birdy.main()

    - birdy=birdy:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - argcomplete
    - lxml
    - owslib
    - nose

  run:
    - python
    - argcomplete
    - lxml
    - owslib
    - nose

test:
  # Python imports
  imports:
    - birdy

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - nosetests -A 'not slow and not online'

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: https://github.com/bird-house/birdy
  license: Apache License v2.0
  summary: 'Birdy provides a commandline tool to work with Web Processing Services (WPS).'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
