{% set version = "0.6.1" %}

package:
  name: birdhouse-birdy
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/birdy.git
  git_tag: v{{ version }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - birdy=birdy.cli.run:cli

requirements:
  build:
    - python
    - setuptools
    - six
    - click
    - lxml
    - owslib >=0.17.0
    - owslib-esgfwps=0.1.0
    - jinja2
    - wrapt
    - funcsigs
    - boltons
  run:
    - python
    - six
    - click
    - lxml
    - owslib >=0.17.0
    - owslib-esgfwps=0.1.0
    - jinja2
    - wrapt
    - funcsigs
    - boltons

test:
  imports:
    - birdy

  requires:
    - pytest

about:
  home: https://github.com/bird-house/birdy
  license: Apache License v2.0
  summary: 'Birdy provides a command-line tool to work with Web Processing Services (WPS).'

extra:
  recipe-maintainers:
    - cehbrecht
