{% set version = "0.2.2" %}

package:
  name: birdhouse-birdy
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/birdy.git
  git_tag: {{ version }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - birdy=birdy:main

requirements:
  build:
    - python
    - setuptools
    - owslib >=0.16.0
  run:
    - python
    - argcomplete
    - lxml
    - owslib >=0.16.0

test:
  imports:
    - birdy

  requires:
    - pytest

about:
  home: https://github.com/bird-house/birdy
  license: Apache License v2.0
  summary: 'Birdy provides a command-line tool to work with Web Processing Services (WPS).'

extra:
  recipe-maintainers:
    - cehbrecht
