package:
  name: qa-dkrz
  version: '0.5.9'

build:
  number: 1

source:
  git_url: https://github.com/IS-ENES-Data/QA-DKRZ.git
  git_tag: master

requirements:
  build:
    - libnetcdf
    - hdf5 >=1.8.15
    - zlib
    - udunits2 >=2.2.20
    - libuuid
    - wget
    - expat
    - curl
    - gcc
  run:
    - libnetcdf
    - hdf5 >=1.8.15
    - zlib
    - udunits2 >=2.2.20
    - libuuid
    - expat
    - curl
    - wget
    - libgcc
test:
  commands:
    - dkrz-cf-checker -h
    - qa-dkrz -h

about:
  home: http://qa-dkrz.readthedocs.org/en/latest/
  summary: 'Quality Assurance checker of meta-data in climate data sets (netCDF files) for CF conformance and CMIP5 and CORDEX projects conventions.'
  license: Copyright DKRZ
