package:
  name: qa-dkrz
  version: '0.6.0'

build:
  number: 1

source:
  #git_url: https://github.com/IS-ENES-Data/QA-DKRZ.git
  git_url: https://github.com/bird-house/QA-DKRZ
  #git_tag: master
  git_tag: birdhouse

requirements:
  build:
    - libnetcdf 4.4.*
    - jpeg 9b
    - zlib
    - udunits2
    - libuuid
    - expat
    - curl
    - gcc
  run:
    - libnetcdf 4.4.*
    - jpeg 9b
    - zlib
    - udunits2
    - libuuid
    - expat
    - curl
    - libgcc
test:
  commands:
    - dkrz-cf-checker -h
    - qa-dkrz -h

about:
  home: http://qa-dkrz.readthedocs.org/en/latest/
  summary: 'Quality Assurance checker of meta-data in climate data sets (netCDF files) for CF conformance and CMIP5 and CORDEX projects conventions.'
  license: Copyright DKRZ
