
package:
    name: nginx
    version: 1.10.1

source:
    fn: nginx-1.10.1.tar.gz
    url: http://nginx.org/download/nginx-1.10.1.tar.gz
    md5: 3ca4a37931e9fa301964b8ce889da8cb

build:
    number: 0

requirements:
    build:
        - pcre
        - openssl
        - zlib

    run:
        - pcre 
        - openssl
        - zlib

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license
    summary: nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP proxy server.

