
package:
    name: nginx
    version: 1.8.0

source:
    fn: nginx-1.8.0.tar.gz
    url: http://nginx.org/download/nginx-1.8.0.tar.gz
    md5: d1b55031ae6e4bce37f8776b94d8b930

build:
    number: 0

requirements:
    build:
        - pcre
        - openssl
        - zlib

    run:
        - pcre 
        - openssl
        - zlib

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license
    summary: nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP proxy server.

