{% set version = "0.1.0" %}

package:
  name: owslib-esgfwps
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/OWSLib-esgfwps.git
  git_tag: v{{ version }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
    - setuptools
    - lxml
    - owslib >=0.17.0
  run:
    - python
    - lxml
    - owslib >=0.17.0

test:
  imports:
    - owslib_esgfwps

about:
  home: https://geopython.github.io/OWSLib-esgfwps
  license: Apache License v2.0
  summary: 'OWSLib extension for ESGF WPS'

extra:
  recipe-maintainers:
    - cehbrecht
