{% set version = "0.1.0" %}

package:
  name: owslib-esgfwps
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/OWSLib-esgfwps.git
  # git_tag: v{{ version }}
  branch: pingudev

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - owslib
  run:
    - python
    - owslib

test:
  imports:
    - owslib
    - owslib_esgfwps

about:
  home: https://geopython.github.io/OWSLib-esgfwps
  license: Apache Software License 2.0
  summary: 'OWSLib extension for ESGF WPS'

extra:
  recipe-maintainers:
    - cehbrecht
