package:
  name: emu
  version: !!str 0.8.0

source:
  git_url: https://github.com/bird-house/emu.git
  git_rev: master

build:
  number: 0 
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pywps >=4.1
    - click
    - jinja2
  run:
    - python
    - pywps >=4.1
    - click
    - jinja2

test:
  # Python imports
  imports:
    - emu

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - emu --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    #- pytest

about:
  home: https://github.com/bird-house/emu
  license: Apache License 2.0
  summary: 'OGC Web Processing Service with processes for testing and demo.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
