package:
  name: dispel4py
  version: !!str 1.1.2

source:
  fn: dispel4py-1.1.2.tar.gz
  url: https://pypi.python.org/packages/source/d/dispel4py/dispel4py-1.1.2.tar.gz
  md5: 6e858e575fa875411face95c2b40b062
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - birdhouse-birdy = birdhouse-birdy:main
    #

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - networkx
    - mpi4py  
    - flake8

  run:
    - python
    - networkx
    - mpi4py  
    - flake8

test:
  # Python imports
  imports:
    - dispel4py

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dispel4py/dispel4py
  license: Apache License v2.0
  summary: 'Dispel4py is a Python library used to describe abstract workflows for distributed data-intensive applications.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
