{% set version = "1.2.1" %}

package:
  name: dispel4py
  version: {{ version }}

source:
  git_url: https://github.com/dispel4py/dispel4py.git
  git_tag: master

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - networkx
    - numpy
  run:
    - python
    - networkx
    - numpy
test:
  imports:
    - dispel4py

  requires:
    - pytest

about:
  home: https://github.com/dispel4py/dispel4py
  license: Apache License v2.0
  summary: 'A Python library to describe abstract workflows for distributed data-intensive applications.'

extra:
  recipe-maintainers:
    - cehbrecht
