package:
  name: pbr
  version: "0.10.7"

source:
  fn: pbr-0.10.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pbr/pbr-0.10.7.tar.gz
  md5: 3f523231e709ad028497d7af557bf2fb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pbr = pbr:main
    #
    # Would create an entry point called pbr that calls pbr.main()

    - pbr = pbr.cmd.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - pip

test:
  # Python imports
  imports:
    - pbr

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pbr --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/pbr
  license: Apache Software License
  summary: 'Python Build Reasonableness'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
