package:
    name: ncwms2
    version: 1.0.2

source:
    fn: ncWMS2.war 
    url: https://github.com/Reading-eScience-Centre/edal-java/releases/download/edal-1.0.2/ncWMS2.war
    md5: 7faab11dc567a3acd0b689a2a435d5ae 

build:
    number: 0

requirements:
    build:
        - apache-tomcat

    run:
        - apache-tomcat

about:
    home: http://reading-escience-centre.github.io/edal-java/
    license: Copyright (c) 2010 The University of Reading
    summary: ncWMS is a Web Map Service for displaying environmental data

