package:
    name: ncwms2
    version: 2.2.7

source:
    fn: ncWMS2.war
    url: https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-2.2.7/ncWMS2.war
    md5: 4c3bfadf31708595529bbb51c9be2697

build:
    number: 0
    noarch: True

requirements:
    build:
        - apache-tomcat

    run:
        - apache-tomcat

about:
    home: http://reading-escience-centre.github.io/edal-java/
    license: Copyright (c) 2010 The University of Reading
    summary: ncWMS is a Web Map Service for displaying environmental data

