{% set version = "2.4.1" %}

package:
  name: ncwms2
  version: {{ version }}

source:
  fn: ncWMS2.war
  url: https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-{{ version }}/ncWMS2.war
  sha256: dbe8dfe643f5650635ca2d9d1ea1cd773cd368567a8ef03d24ef94f7be74f896

build:
  number: 0
  noarch: True

requirements:
  build:
    - apache-tomcat
  run:
    - apache-tomcat

about:
  home: http://reading-escience-centre.github.io/edal-java/
  license: Copyright (c) 2010 The University of Reading
  summary: ncWMS is a Web Map Service for displaying environmental data

extra:
  recipe-maintainers:
    - cehbrecht
