package:
  name: libgd
  version: 2.1.1

source:
  fn: libgd-2.1.1.tar.gz
  url: https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz

build:
  number: 0

requirements:
  build:
    - zlib
    - freetype
    - jpeg
    - libpng >=1.6
    - libtiff

  run:
    - zlib
    - freetype
    - jpeg
    - libpng
    - libtiff

about:
  home: http://libgd.bitbucket.org
  license: 

# vim:set ts=8 sw=2 sts=2 tw=78 et:
