package:
  name: cdo
  version: 1.6.8

source:
  fn: cdo-1.6.8.tar.gz
  url: https://code.zmaw.de/attachments/download/10030/cdo-1.6.8.tar.gz
  md5: 8f91f086db2d7c71b81bffd0a7817dfd

build:
  number: 1

requirements:
  build:
    - jasper
    - grib_api
    - libnetcdf
    - proj4
  run:
    - jasper
    - grib_api
    - libnetcdf
    - proj4

test:
  commands:
    # DYLD_LIBRARY_PATH=/Users/pingu/anaconda/lib
    - cdo -h

about:
  home: https://code.zmaw.de/projects/cdo
  license: GNU General Public License v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
  summary: CDO is a collection of command line Operators to manipulate and analyse Climate and NWP model Data.
