package:
    name: esmvaltool
    version: 2.0.0

source:
    git_url: https://github.com/cehbrecht/ESMValTool.git
    git_branch: demo-magic-workshop

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
    run:
        - python
        - cython
        - yamale
        - esgf-pyclient
        - basemap
        - cartopy
        - cf_units
        - iris
        - ncl 6.4.*
        # ncl pacch
        #- poppler 0.52
        #- xerces-c 3.1
        #- gsl
        # ncl patch end
        - netcdf4
        - numba 0.35.0
        - numpy
        - pillow # providing PIL package
        #- python-cdo
        - python-stratify
        - pyyaml
        - scipy
        - shapely
        - six

about:
    home: http://www.esmvaltool.org/
    license: Apache License version 2.0
    summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
