package:
    name: esmvaltool
    version: 1.1.0

source:
    git_url: https://github.com/cehbrecht/ESMValTool.git
    git_branch: pingudev

build:
    number: 3

requirements:
    build:
        - python

    run:
        - python
        - cython
        - esgf-pyclient
        #- scientificpython
        # iris
        #- iris
        #- basemap
        #- matplotlib 1.5.3
        #- cartopy 0.15.1
        # ncl
        - ncl 6.4.0
        - libnetcdf 4.4.1.1
        #- hdf5 1.8.17
        #- hdf4 4.2.12
        - xorg-libsm 1.2.2
        #- icu 58.1
        - xorg-libxrender
        - xorg-libxext

about:
    home: http://www.esmvaltool.org/
    license: Apache License version 2.0
    summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
