package:
  name: lapack95
  version: 3.0.0

source:
  fn: lapack95.tgz
  url: http://www.netlib.org/lapack95/lapack95.tgz 
  sha1: f9e788b8c3b6d8dc19c73007840455c7ada6926a

build:
  number: 7

requirements:
  build:
    - gcc

  run:
    - libgfortran

about:
  home: http://www.netlib.org/lapack95
  license: BSD
  summary: LAPACK95 is a Fortran95 interface to LAPACK. 
