package:
  name: geolinks
  version: "0.0.1"

source:
  fn: geolinks-0.0.1.tar.gz
  url: https://pypi.python.org/packages/source/g/geolinks/geolinks-0.0.1.tar.gz
  md5: 51e43aa0afd611cebc986ec411f24d40
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - geolinks = geolinks:main
    #
    # Would create an entry point called geolinks that calls geolinks.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - geolinks

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/geopython/geolinks
  license: MIT License
  summary: 'Utilities to deal with geospatial links'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
