package: owslib
user: birdhouse
before_script:
  - conda update -n root conda-build binstar anaconda-build
  - conda config --add channels birdhouse
script:
  - conda build .
build_targets:
  - conda
