package:
  name: owslib
  version: !!str 0.9.0

source:
  git_url: https://github.com/bird-house/OWSLib.git
  git_branch: birdhouse
#  fn: OWSLib-0.9.0.tar.gz
#  url: https://pypi.python.org/packages/source/O/OWSLib/OWSLib-0.9.0.tar.gz
#  md5: e511e8bdddce0e59abefc892f090e033
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - owslib = owslib:main
    #
    # Would create an entry point called owslib that calls owslib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 5

requirements:
  build:
    - python
    - setuptools
    - requests
    - python-dateutil
    - pytz
    - lxml
    - pyproj

  run:
    - python
    - setuptools
    - requests
    - python-dateutil
    - pytz
    - lxml
    - pyproj

test:
  # Python imports
  imports:
    - owslib
    - owslib.coverage
    - owslib.feature
    - owslib.swe
    - owslib.wps

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://geopython.github.io/OWSLib
  license: BSD License
  summary: 'OGC Web Service utility library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
