{% set version = "0.17.1b2" %}

package:
  name: owslib
  version: {{ version }}

source:
  git_url: https://github.com/bird-house/OWSLib.git
  git_branch: birdhouse

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - pytz
    - requests
    - pyproj
    - lxml

test:
  imports:
    - owslib.coverage
    - owslib.waterml
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib
    - owslib.feature
    - owslib.swe

about:
  home: https://geopython.github.io/OWSLib
  license: BSD-3-Clause
  # see https://github.com/geopython/OWSLib/pull/518
  #license_file: LICENSE
  summary: 'OGC Web Service utility library'

extra:
  recipe-maintainers:
    - cehbrecht
