{% set version = "0.17.0" %}

package:
  name: owslib
  version: {{ version }}

source:
  git_url: https://github.com/geopython/OWSLib.git
  git_branch: master

build:
  number: 3 
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil
    - pytz
    - requests
    - pyproj
    - lxml

test:
  imports:
    - owslib
    - owslib.wps
    - owslib.wms

about:
  home: https://geopython.github.io/OWSLib
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'OGC Web Service utility library.'

extra:
  recipe-maintainers:
    - cehbrecht
