package:
  name: cfunits
  version: 1.0.0

source:
  fn: cfunits-0.9.6.tar.gz
  url: https://bitbucket.org/cfpython/cfunits-python/downloads/cfunits-1.0.tar.gz
  md5: ac74742daf7f5afc4d758ed2d70d46e2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - udunits
    - numpy
    - netcdf4

  run:
    - python
    - udunits
    - numpy
    - netcdf4

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  summary: 'A python interface to UNIDATAs Udunits-2 package with CF extensions.'
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
