package:
  name: cfunits
  version: 0.9.6

source:
  fn: cfunits-0.9.6.tar.gz
  url: http://cfunits-python.googlecode.com/files/cfunits-0.9.6.tar.gz
  md5: e876322cac0d939b5dd9ce53ad708b7e

build:
  number: 3

requirements:
  build:
    - python
    - setuptools
    - udunits
    - netcdf4 ==1.1.1

  run:
    - python
    - udunits
    - netcdf4 ==1.1.1

about:
  home: https://code.google.com/p/cfunits-python/
  summary: A python interface to UNIDATA's Udunits-2 package with CF extensions.
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
