package:
    name: cfchecker
    version: 2.0.8

source:
    fn: cfchecker-2.0.8.tar.gz
    url: https://pypi.python.org/packages/source/c/cfchecker/cfchecker-2.0.8.tar.gz
    md5: c8d786c3f442ab75ab53fbc7b05aa601

build:
    number: 0

    entry_points:
        - cfchecks = cfchecker:cfchecks_main

requirements:
    build:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits

    run:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits

test:
    commands:
        - cfchecks -h
    imports:
        - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD
  summary: The NetCDF Climate Forcast Conventions compliance checker.
