package:
    name: cfchecker
    version: 2.0.9

source:
    fn: cfchecker-2.0.9.tar.gz
    url: https://pypi.python.org/packages/source/c/cfchecker/cfchecker-2.0.9.tar.gz
    md5: e36c556454e21d88aaa9f0394429032f

build:
    number: 0

    entry_points:
        - cfchecks = cfchecker:cfchecks_main

requirements:
    build:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits2

    run:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits2

test:
    commands:
        - cfchecks -h
    imports:
        - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD
  summary: The NetCDF Climate Forcast Conventions compliance checker.
