package:
    name: cfchecker
    version: 2.0.7

source:
    fn: cfchecker-2.0.7.tar.gz
    url: https://pypi.python.org/packages/source/c/cfchecker/cfchecker-2.0.7.tar.gz
    md5: 993f538bf58027416b777be8c97266a5

build:
    number: 0

    entry_points:
        - cfchecks = cfchecker:cfchecks_main

requirements:
    build:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits

    run:
        - python
        - setuptools
        - numpy
        - cdat-lite
        - udunits

test:
    commands:
        - cfchecks -h
    imports:
        - cfchecker

about:
  home: https://pypi.python.org/pypi/cfchecker
  license: BSD
  summary: The NetCDF Climate Forcast Conventions compliance checker.
