
package:
    name: pywps
    version: !!str 3.2.6

source:
    git_url: https://github.com/bird-house/pywps.git
    git_tag: pingudev-3.2

build:
    number: 1

requirements:
    build:
        - python <3
        - setuptools
        - htmltmpl
        - lxml >=3.5.0
        - python-magic

    run:
        - python
        - htmltmpl
        - lxml >=3.5.0
        - python-magic

test:
    imports:
        - pywps

    #commands:
    #    -

about:
    home: https://github.com/geopython/PyWPS
    license: GPLv2
    summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.
