package:
  name: gdal
  version: !!str patch_1.11.1

source:
  fn: gdal-1.11.1.tar.gz
  url: http://download.osgeo.org/gdal/1.11.1/gdal-1.11.1.tar.gz
  md5: 7555f55855f613be49e6508eed0ac3fa
  patches:
    - adaguc.patch

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - xerces-c
    - geos
    - proj4
    - hdf5
    - libnetcdf
    - libpng
    - jpeg
    - udunits
    - jasper
  run:
    - python
    - numpy
    - xerces-c
    - geos
    - proj4
    - hdf5
    - libnetcdf
    - libpng
    - jpeg
    - udunits
    - jasper
test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 1.11.1. Built with all command line tools and with GEOS and HDF5 support.
