
package:
    name: apache-tomcat
    version: 7.0.59

source:
    fn: apache-tomcat-7.0.59.tar.gz 
    url: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/tomcat/tomcat-7/v7.0.59/bin/apache-tomcat-7.0.59.tar.gz
    md5: ec570258976edf9a833cd88fd9220909

build:
    number: 0

requirements:
    build:

    run:

test:
    commands:
        - catalina.sh version

about:
    home: http://tomcat.apache.org/
    license: Apache License v2.0

