
package:
    name: apache-tomcat
    version: 7.0.63

source:
    fn: apache-tomcat-7.0.63.tar.gz 
    url: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/tomcat/tomcat-7/v7.0.63/bin/apache-tomcat-7.0.63.tar.gz
    md5: c771aa7b2903691d6034f6584c95304c

build:
    number: 0

requirements:
    build:
      - java-jdk

    run:
      - java-jdk

test:
    commands:
        - catalina.sh version

about:
    home: http://tomcat.apache.org/
    summary: 'Apache Tomcat is an open source software implementation of the Java Servlet, JavaServer Pages, Java Expression Language and Java WebSocket technologies.'
    license: Apache License v2.0

