{% set version = "7.0.77" %}

package:
    name: apache-tomcat
    version: {{ version }}

source:
    fn: apache-tomcat-{{ version }}.tar.gz 
    url: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/tomcat/tomcat-7/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz
    md5: 82f3a69298a0e506de0f6c3c1295953d

build:
    number: 0
    noarch: True

requirements:
    build:
      - openjdk

    run:
      - openjdk

#test:
#    commands:
#        - catalina.sh version

about:
    home: http://tomcat.apache.org/
    summary: 'Apache Tomcat is an open source software implementation of the Java Servlet, JavaServer Pages, Java Expression Language and Java WebSocket technologies.'
    license: Apache License v2.0

