package:
    name: solr 
    version: "5.2.1" 

source:
    fn: solr-5.2.1.tgz
    url: http://archive.apache.org/dist/lucene/solr/5.2.1/solr-5.2.1.tgz
    md5: 50b87813e33665512c78ab056842c4d3
    
build:
    number: 2
    noarch: True

requirements:
    build:
        - openjdk

    run:
        - openjdk
test:
    commands:
        - solr start -help

about:
    home: http://lucene.apache.org/solr/
    summary: 'Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene'
    license: Apache 2.0 license
