package:
    name: solr 
    version: "6.4.0" 

source:
    fn: solr-6.4.0.tgz
    url: http://archive.apache.org/dist/lucene/solr/6.4.0/solr-6.4.0.tgz
    sha256: 50b87813e33665512c78ab056842c4d3
    
build:
    number: 0
    noarch: True

requirements:
    build:
        - openjdk

    run:
        - openjdk
test:
    commands:
        - solr start -help

about:
    home: http://lucene.apache.org/solr/
    summary: 'Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene'
    license: Apache 2.0 license
