{% set version = "5.5.4" %}

package:
    name: solr 
    version: {{ version }} 

source:
    fn: solr-{{ version }}.tgz
    url: http://archive.apache.org/dist/lucene/solr/{{ version }}/solr-{{ version }}.tgz
    sha256: c1528e4afc9a0b8e7e5be0a16f40bb4080f410d502cd63b4447d448c49e9f500
    
build:
    number: 0
    noarch: True

requirements:
    build:
        - openjdk

    run:
        - openjdk
test:
    commands:
        - solr start -help

about:
    home: http://lucene.apache.org/solr/
    summary: 'Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene'
    license: Apache 2.0 license
