
package:
    name: pywps
    version: !!str 4.0.0_rc2

source:
    git_url: https://github.com/bird-house/pywps
    git_tag: pingudev-4

build:
    number: 4

requirements:
    build:
        - python
        - setuptools
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - flufl.enum # [py27]
        - python-dateutil
    run:
        - python
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - gdal 
        - flufl.enum # [py27]
        - python-dateutil
test:
    imports:
        - pywps

    #commands:
    #    -

about:
    home: https://github.com/geopython/PyWPS
    license: MIT License
    summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.
