{% set name = "pywps" %}
{% set version = "4.0.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/bird-house/pywps
    git_tag: pingudev-4

build:
    number: 29
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - gdal
        - flufl.enum # [py27]
        - python-dateutil
        - requests
        - psycopg2
        - dill
        - drmaa
test:
    imports:
        - pywps

about:
    home: http://pywps.org/
    license: MIT
    summary: 'PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.'

extra:
  recipe-maintainers:
    - cehbrecht
