
package:
    name: pywps
    version: !!str 4.0.0

source:
    git_url: https://github.com/bird-house/pywps
    git_tag: pingudev-4

build:
    number: 8
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - flufl.enum # [py27]
        - python-dateutil
    run:
        - python
        - owslib
        - jsonschema
        - werkzeug
        - lxml
        - sqlalchemy
        - gdal 
        - flufl.enum # [py27]
        - python-dateutil
test:
    imports:
        - pywps

about:
    home: http://pywps.org/
    license: MIT
    summary: 'PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.'

extra:
  recipe-maintainers:
    - cehbrecht
