package:
  name: pyproj
  version: !!str 1.9.4

source:
  fn: pyproj-1.9.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pyproj/pyproj-1.9.4.tar.gz
  md5: b0a060465b117dd6c1b37e14f22382aa
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyproj = pyproj:main
    #
    # Would create an entry point called pyproj that calls pyproj.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - proj4

  run:
    - python
    - proj4

test:
  # Python imports
  imports:
    - pyproj

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/pyproj/
  license: OSI Approved
  summary: 'Python interface to PROJ.4 library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
