package:
  name: bird-feeder
  version: "0.1.1"

source:
  fn: bird-feeder-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bird-feeder/bird-feeder-0.1.1.tar.gz
  md5: d981d0db668f6384c32c209864836832
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bird-feeder = bird-feeder:main
    #
    # Would create an entry point called bird-feeder that calls bird-feeder.main()

    - birdfeeder=birdfeeder:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argcomplete
    - pysolr
    - threddsclient
    - python-dateutil
    - nose

  run:
    - python
    - argcomplete
    - pysolr
    - threddsclient
    - python-dateutil
    - nose

test:
  # Python imports
  imports:
    - birdfeeder

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - birdfeeder --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bird-house/bird-feeder
  license: Apache License v2.0
  summary: 'Bird Feeder publishes Thredds metadata catalogs to a Solr index service with birdhouse schema.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
